name: Deploy to EC2
on:
  push:
    branches: [ "frontend" ]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            if [ ! -d "/var/www/myapp" ]; then
              mkdir -p /var/www/myapp
            fi
            cd /var/www/myapp
            if [ ! -d ".git" ]; then
              git clone https://github.com/johnnylee2044/Pos-System.git .
            else
              git pull
            fi
            npm install
            pm2 restart all
          EOF
