name: Deploy to EC2

on:
  push:
    branches:
      - frontend-pos   # Change this to your actual branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            # Update and install dependencies
            sudo yum update -y
            sudo yum install git -y
            curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
            sudo yum install -y nodejs

            # Clone the repo if it doesn't exist
            if [ ! -d "Pos-System" ]; then
              git clone https://github.com/johnnylee2044/Pos-System.git
            fi

            cd Pos-System
            git pull origin frontend-pos

            # Install dependencies and run app
            npm install

            # Kill any running app on port 3000
            fuser -k 3000/tcp || true

            # Start app in background
            nohup npm run start > output.log 2>&1 &
          EOF
